---
- name: Restart caddy
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: caddy-cloudflare
    state: restarted  # this works even if deploying the services for the first time
