[project]
name = "ansible-media-server"
version = "0.1.0"
description = "Ansible playbooks for media server setup"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=12.1.0",
    "ansible-core>=2.19.0",
    "ansible-dev-tools>=25.8.0",
]

[tool.uv]
package = false
