- name: Set up Caddy for reverse proxying
  hosts: homeserver
  become: true
  gather_facts: true

  tasks:
    - name: Set up Caddy for reverse proxying services
      ansible.builtin.include_role:
        name: "caddy-podman"
      vars:
        caddy_timezone: "{{ timezone }}"
        caddy_user_id: "{{ podman_user_id }}"
        caddy_group_id: "{{ podman_group_id }}"
        caddy_host_ip_is_static: "{{ caddy.host_ip_is_static }}"
        # Secrets in group_vars/all/vault.yml
        caddy_cloudflare_api_token: "{{ v_caddy_cloudflare_api_token }}"
        caddy_cloudflare_zone_id: "{{ v_caddy_cloudflare_zone_id }}"
