- name: Run common setup steps
  hosts: homeserver
  become: true
  gather_facts: false

  tasks:
    - name: Add podman group for podman user
      tags: users
      ansible.builtin.group:
        name: podman
        state: present
        gid: "{{ podman_group_id }}"

    - name: Add podman user to run containers under
      tags: users
      ansible.builtin.user:
        name: podman
        uid: "{{ podman_user_id }}"
        append: true
        # This needs to be a hashed password
        password: "{{ v_podman_user_password }}"
        groups:
          - render
          - video
          - podman

    - name: Install python3-libdnf5
      tags: packages
      ansible.builtin.command: dnf install -y python3-libdnf5
      when: ansible_os_family == 'RedHat'
